name: 'Test the custom action'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Test the custom action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom action
        id: time
        uses: ./ # Use the custom action in the repository

      - name: Use the time output
        run: echo "${{ steps.time.outputs.date_time }}"
